import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { LumeIssue } from './AIEngine';

export class TicketManager {
    private projectRoot: string;

    constructor(projectRoot: string) {
        this.projectRoot = path.resolve(projectRoot);
    }

    public writeTemplate(issue: LumeIssue, targetFile: string): string {
        const sanitizedFile = path.normalize(targetFile);
        if (sanitizedFile.includes('..') || path.isAbsolute(sanitizedFile)) {
            throw new Error('Invalid file path: directory traversal attempt detected');
        }

        const issuesDir = path.join(this.projectRoot, '.github', 'ISSUES');
        
        try {
            if (!fs.existsSync(issuesDir)) {
                fs.mkdirSync(issuesDir, { recursive: true });
            }
        } catch (e) {
            throw new Error(`Failed to create issues directory: ${e instanceof Error ? e.message : String(e)}`);
        }

        const sanitize = (input: string, maxLen: number = 500): string => {
            return (input || '')
                .replace(/[\r\n]/g, ' ')
                .slice(0, maxLen);
        };

        const template = `## 🦋 LumeMoth Security & Architecture Report

### File context
**File**: \`${sanitizedFile}\`
**Line**: ${issue.line}
**Violated Layer**: \`${issue.layer}\`

### What failed?
**Severity**: ${issue.severity}
${sanitize(issue.problem, 500)}

### Assumed Developer Intent
${sanitize(issue.intent, 500)}

### Required Refactoring / Explanation why this is bad
${sanitize(issue.explanation, 1000)}

---
*Auto-generated by LumeMoth Agentic Engine.*
`;

        const filename = `lumemoth_ticket_${Date.now()}.md`;
        const filePath = path.join(issuesDir, filename);
        
        try {
            fs.writeFileSync(filePath, template, 'utf-8');
        } catch (e) {
            throw new Error(`Failed to write ticket template to ${filePath}: ${e instanceof Error ? e.message : String(e)}`);
        }

        return filePath;
    }

    public createRemoteIssue(issue: LumeIssue, targetFile: string): boolean {
        const title = `[${issue.layer}] LumeMoth finding in ${targetFile}`;
        
        let bodyPath: string;
        try {
            bodyPath = this.writeTemplate(issue, targetFile);
        } catch (e) {
            console.error('Failed to create ticket template:', e instanceof Error ? e.message : String(e));
            return false;
        }

        // Validate that bodyPath is within projectRoot (prevent injection)
        const resolvedBodyPath = path.resolve(bodyPath);
        const resolvedProjectRoot = path.resolve(this.projectRoot);
        if (!resolvedBodyPath.startsWith(resolvedProjectRoot)) {
            console.error('Security validation failed: body path is outside project root');
            return false;
        }

        try {
            execFileSync('gh', ['--version'], { stdio: 'ignore' });
            execFileSync('gh', ['issue', 'create', '--title', title, '--body-file', bodyPath], {
                stdio: 'inherit',
                cwd: this.projectRoot
            });
            return true;
        } catch (e) {
            const errorMsg = e instanceof Error ? e.message : String(e);
            console.error(`Failed to create GitHub issue: ${errorMsg}`);
            console.error('Possible causes:');
            console.error('  - GitHub CLI (gh) is not installed');
            console.error('  - Not authenticated with GitHub (run: gh auth login)');
            console.error('  - Not in a Git repository or not on GitHub');
            return false;
        }
    }
}
