import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { LumeIssue } from './AIEngine';

export class TicketManager {
    private projectRoot: string;

    constructor(projectRoot: string) {
        this.projectRoot = projectRoot;
    }

    /**
     * Generates a tailored ticket template for a manually reviewable issue.
     */
    public writeTemplate(issue: LumeIssue, targetFile: string): string {
        const issuesDir = path.join(this.projectRoot, '.github', 'ISSUES');
        if (!fs.existsSync(issuesDir)) {
            fs.mkdirSync(issuesDir, { recursive: true });
        }

        const template = `## 🦋 LumeMoth Security & Architecture Report

### File context
**File**: \`${targetFile}\`
**Line**: ${issue.line}
**Violated Layer**: \`${issue.layer}\`

### What failed?
**Severity**: ${issue.severity}
${issue.problem}

### Assumed Developer Intent
${issue.intent}

### Required Refactoring / Explanation why this is bad
${issue.explanation}

---
*Auto-generated by LumeMoth Agentic Engine.*
`;

        const filename = `lumemoth_ticket_${Date.now()}.md`;
        const filePath = path.join(issuesDir, filename);
        fs.writeFileSync(filePath, template, 'utf-8');

        return filePath;
    }

    /**
     * Attempts to create the issue automatically on GitHub.
     */
    public createRemoteIssue(issue: LumeIssue, targetFile: string): boolean {
        const title = `[${issue.layer}] LumeMoth finding in ${targetFile}`;
        const bodyPath = this.writeTemplate(issue, targetFile);

        try {
            // Dry run gh cmd execution check
            execSync('gh --version', { stdio: 'ignore' });

            // Execute ticket creation
            execSync(`gh issue create --title "${title}" --body-file "${bodyPath}"`, {
                stdio: 'inherit',
                cwd: this.projectRoot
            });
            return true;
        } catch (e) {
            return false; // GH CLI not available or not logged in
        }
    }
}
