import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { LumeIssue } from './AIEngine';

export class TicketManager {
    private projectRoot: string;

    constructor(projectRoot: string) {
        this.projectRoot = path.resolve(projectRoot);
    }

    public writeTemplate(issue: LumeIssue, targetFile: string): string {
        const sanitizedFile = path.normalize(targetFile);
        if (sanitizedFile.includes('..') || path.isAbsolute(sanitizedFile)) {
            throw new Error('Invalid file path: directory traversal attempt detected');
        }

        const issuesDir = path.join(this.projectRoot, '.github', 'ISSUES');
        if (!fs.existsSync(issuesDir)) {
            fs.mkdirSync(issuesDir, { recursive: true });
        }

        const sanitize = (input: string, maxLen: number = 500): string => {
            return (input || '')
                .replace(/[\r\n]/g, ' ')
                .slice(0, maxLen);
        };

        const template = `## 🦋 LumeMoth Security & Architecture Report

### File context
**File**: \`${sanitizedFile}\`
**Line**: ${issue.line}
**Violated Layer**: \`${issue.layer}\`

### What failed?
**Severity**: ${issue.severity}
${sanitize(issue.problem, 500)}

### Assumed Developer Intent
${sanitize(issue.intent, 500)}

### Required Refactoring / Explanation why this is bad
${sanitize(issue.explanation, 1000)}

---
*Auto-generated by LumeMoth Agentic Engine.*
`;

        const filename = `lumemoth_ticket_${Date.now()}.md`;
        const filePath = path.join(issuesDir, filename);
        fs.writeFileSync(filePath, template, 'utf-8');

        return filePath;
    }

    public createRemoteIssue(issue: LumeIssue, targetFile: string): boolean {
        const title = `[${issue.layer}] LumeMoth finding in ${targetFile}`;
        const bodyPath = this.writeTemplate(issue, targetFile);

        try {
            execFileSync('gh', ['--version'], { stdio: 'ignore' });
            execFileSync('gh', ['issue', 'create', '--title', title, '--body-file', bodyPath], {
                stdio: 'inherit',
                cwd: this.projectRoot
            });
            return true;
        } catch (e) {
            return false;
        }
    }
}
